### ISSUE TITLE
error: failed to build archive: File lib.rmeta exceeds size limit

### ISSUE THREAD

**Issue by ZLiu094** [novafacing/qemu-rs#11]
```
error: failed to build archive: File lib.rmeta exceeds size limit

error: could not compile `qemu` (lib) due to 1 previous error
```

I met this error when I compiled with qemu-rs after 8.2. It's ok with 8.1

Rustc version: rustc 1.77.0-nightly (11f32b73e 2024-01-31)
Cargo.toml:
```toml
qemu = { version = "8.2.2-v0", features = [
  "plugins",
  "debug-info",
  "x86_64-linux-user",
  "enable-feature-capstone",
  "enable-feature-avx2",
  "enable-feature-avx512bw",
  "enable-feature-avx512f",
  "binaries",
  "enable-feature-kvm",
] }

qemu-plugin = { version = "8.2.2-v0" }
```

I guess you have no such problems but still want to ask if you know the reason -.-.

**Comment by ZLiu094** [comment]
FYI: It was compiled successfully without the debug-info feature.

**Comment by novafacing** [comment]
Makes sense! I'll add this to the feature description (and remove debug-info from default if it's there -- I don't recall). Thank you for the report and workaround!

**Comment by novafacing** [comment]
Cleaned up the example and added a note to the feature.
