### ISSUE TITLE
crashes during calls to `g_free` on windows.

### ISSUE THREAD

**Issue by tocklime** [novafacing/qemu-rs#13]
https://github.com/novafacing/qemu-rs/blob/ed66662b21e0a217eb240543415b6462689e7a69/qemu-plugin/src/lib.rs#L128 

Now I come to try this again (via the `disas()` function), it seems it doesn't work - I get segfaults. I thought I had seen it work previously. Maybe I was wrong. Judging from gdb backtraces it looks like there's several `RtlCreateHeap` calls, and I guess we must be trying to free in the wrong heap, or something. It's dying inside a `RtlFreeHeap` call.

Anyway, the magic we need to get the right `g_free` is:
1. Locate the `libglib-2.0-0.dll` DLL in memory.
2. in that, locate the `g_free` function.
3. Call that.

I have this working in principle:
```rust
#[cfg(windows)]
unsafe fn g_free(mem: *mut c_void) {

    use libloading::os::windows::Symbol;
    if !mem.is_null() {
        unsafe {
            let lib = libloading::os::windows::Library::open_already_loaded("libglib-2.0-0.dll").expect("libglib-2.0-0.dll should already be loaded");
            let g_free : Symbol<unsafe extern fn(*mut c_void)> = lib.get(b"g_free").expect("find g_free");
            g_free(mem);
        }
    }
}
```

(using the libloading crate which hides a lot of the windows API nastiness)

which works, but of course it does the lookup on every single call to `g_free` which is no good. I'll keep on this next week and do a lazy_static or something, but just wanted to give you heads up I'm working on something.

**Comment by novafacing** [comment]
Thanks for taking a look at this :)
