### ISSUE TITLE
qemu plugins made with this don't work with Qemu 9.0.0 or later

### ISSUE THREAD

**Issue by tocklime** [novafacing/qemu-rs#15]
The minimum supported plugin version was bumped to 2 in Qemu 9.0.0, and this library makes plugins with v1, and so they do not work in the newest Qemu. You get output like:

```
qemu-system-x86_64: Could not load plugin plugin.dll: plugin requires API version 1, but this QEMU supports only a minimum version of 2
```

**Comment by tocklime** [comment]
Note also that qemu 9.0.0/plugin version 2 includes plugin functions to read register state. It also adds a `#include <glib.h>` to the header, which generate-bindings will have to handle...

**Comment by novafacing** [comment]
Woah, register state! That's definitely worth the hassle to get this fixed up. I'll take a look after work today :)
