### ISSUE TITLE
Disable Default features doesn't seem to exist anymore

### ISSUE THREAD

**Issue by daniel-brenot** [novafacing/qemu-rs#2]
When trying to build using the configuration shown in this repo, I get the following error:
 
thread 'main' panicked at 'Failed to configure qemu:
  stdout:ERROR: unknown option --disable-default-features

is this no longer a feature supported by QEMU? Does this need to be removed?

**Comment by novafacing** [comment]
Likely, I actually just started working on updating this repo for QEMU 8.1 so that fix will be incoming.

**Comment by daniel-brenot** [comment]
Sounds good, thanks! I just removed the arg in my fork for now.

**Comment by novafacing** [comment]
Should be resolved by the latest update.
