### ISSUE TITLE
licensing GPL-2.0-only vs GPL-2.0-or-later

### ISSUE THREAD

**Issue by tocklime** [novafacing/qemu-rs#20]
[You have the license for the plugin as `gpl-2.0-only`](https://github.com/novafacing/qemu-rs/blob/024100cd8d1c10893a8ddec87cff7464d8bc16df/Cargo.toml#L7). 

I believe that `qemu-plugin.h` is `gpl-2.0-or-later`. 

Is there a reason you've gone for 2.0-only, or would the or-later variant be acceptable?

**Comment by novafacing** [comment]
I think -or-later is fine, I'll fix this in v4 (since you're the only other contributor and it seems like you agree 😋)

**Comment by novafacing** [comment]
This will be closed by #21, thanks for the note.

**Comment by tocklime** [comment]
Yes, I agree :)

I'm excited about reading virtual memory too! thanks for sorting that out!
