### ISSUE TITLE
Windows support for plugins

### ISSUE THREAD

**Issue by tocklime** [novafacing/qemu-rs#3]
The qemu-plugin API is much nicer than Cannonball, thanks for that.

Currently, compiling `examples/tiny` on windows (in an msys environment) fails with linker errors:

```
          libqemu_plugin-9b366b86ee3df11c.rlib(qemu_plugin-9b366b86ee3df11c.3nlexlhtiloges53.rcgu.o) : error LNK2019: unresolved external symbol qemu_plugin_bool_parse referenced in function _ZN11qemu_plugin7install5Value3new17hb19820019c468133E
          libqemu_plugin-9b366b86ee3df11c.rlib(qemu_plugin-9b366b86ee3df11c.2vy382h4jhrt5nnw.rcgu.o) : error LNK2019: unresolved external symbol qemu_plugin_tb_n_insns referenced in function _ZN11qemu_plugin16TranslationBlock4size17h6288dd76d0ce99c8E
          libqemu_plugin-9b366b86ee3df11c.rlib(qemu_plugin-9b366b86ee3df11c.2vy382h4jhrt5nnw.rcgu.o) : error LNK2019: unresolved external symbol qemu_plugin_tb_vaddr referenced in function _ZN11qemu_plugin16TranslationBlock5vaddr17hae96755f780c793bE
          libqemu_plugin-9b366b86ee3df11c.rlib(qemu_plugin-9b366b86ee3df11c.2vy382h4jhrt5nnw.rcgu.o) : error LNK2019: unresolved external symbol qemu_plugin_tb_get_insn referenced in function _ZN11qemu_plugin16TranslationBlock11instruction17h95c07ba18e8437e9E
          libqemu_plugin-9b366b86ee3df11c.rlib(qemu_plugin-9b366b86ee3df11c.2vy382h4jhrt5nnw.rcgu.o) : error LNK2019: unresolved external symbol qemu_plugin_insn_data referenced in function _ZN11qemu_plugin11Instruction4data17h2f87c2c1751b7776E
          libqemu_plugin-9b366b86ee3df11c.rlib(qemu_plugin-9b366b86ee3df11c.2vy382h4jhrt5nnw.rcgu.o) : error LNK2019: unresolved external symbol qemu_plugin_insn_size referenced in function _ZN11qemu_plugin11Instruction4size17h2e6d0fb9fd0bdbf3E
          libqemu_plugin-9b366b86ee3df11c.rlib(qemu_plugin-9b366b86ee3df11c.2vy382h4jhrt5nnw.rcgu.o) : error LNK2019: unresolved external symbol qemu_plugin_insn_vaddr referenced in function _ZN11qemu_plugin11Instruction5vaddr17h8f7411fc30897e77E
          libqemu_plugin-9b366b86ee3df11c.rlib(qemu_plugin-9b366b86ee3df11c.2vy382h4jhrt5nnw.rcgu.o) : error LNK2019: unresolved external symbol qemu_plugin_insn_haddr referenced in function _ZN11qemu_plugin11Instruction5haddr17h755f98d4c9ff9ddcE
          ....many more like it....
```

...this is because windows doesn't let you have unresolved references in a DLL (see [notes where I worked on this in base here](https://www.mail-archive.com/qemu-devel@nongnu.org/msg1003961.html)).

To get windows support, we will need:

* A way to acquire or build a `qemu_plugin_api.lib` to help produce the delay-loaded dll, and link from build.rs
  * This is made during qemu building, but it seems expensive to build all of qemu just to be able to make a plugin for it.
  * It can be made from the file [`qemu_plugins.symbols`, as shown in the build.rs snippet here](https://gist.github.com/tocklime/bd91136593353e7cf2907504c3bb5f85#file-build-rs)
* A way to hook into the `__pfnDliFailureHook2` symbol. I have [this working locally](https://gist.github.com/tocklime/bd91136593353e7cf2907504c3bb5f85#file-win_link_hook-rs).

The hook should just work. The build.rs snippet there will need work though - I'm not sure how to get the input file `qemu_plugin_api.def`, and also not sure how to ensure `dlltool` is lying around for use. Given qemu only builds in msys on Windows, it seems reasonable to expect an msys environment/rust target for this.

Anyway, I'm just trying to collate my notes here for comment. Happy to assemble a PR if we can work work out the details.

**Comment by novafacing** [comment]
Hmm interesting, I guess even msys binutils doesnt allow for whatever link arg `#[linkage = "weak"]` ends up emitting then (which doesn't give me much hope for msvc either). Not too surprising. What would really be nice is to solve this at a library level instead of having a big document of "you need to do XY and Z in your crate for this to work" so if we can get it working in qemu-plugin's build rs that would be ideal (and if we can come up with something for Linux/macos which doesn't need nightly that would be nice too.

**Comment by novafacing** [comment]
I think we can call this good, there's some more to do on Windows I think in the future but initial support is working.
